/// Flutter icons Keodam_footer
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Keodam_footer
///      fonts:
///       - asset: fonts/Keodam_footer.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class Keodam_footer {
  Keodam_footer._();

  static const _kFontFam = 'KeodamFooterIcon';
  static const String? _kFontPkg = null;

  static const IconData explore_icon_selected = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData matching_icon_default = IconData(
    0xe803,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData mypage_icon_default = IconData(
    0xe805,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData feed_icon_selected = IconData(
    0xe806,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
